#!/usr/bin/python3
"""factorize given set of numbers in a file to product of two small numbers"""
#!/usr/bin/env python3
""" Factor numbers """
from sys import argv
from math import sqrt


def factorize(number_to_check):
    """"find two small numbers that multiply to give a given number"""
    i = 2
def open_read_file(file_name):
    """read from file
    add to array
    """
    with open(file_name, "r", encoding="utf-8") as file:
        lines = file.readlines()
    number_to_factor = []
    for line in lines:
        number_to_factor.append(int(line))
    return number_to_factor

    if number_to_check < 2:
        return

    while number_to_check % i:
        i += 1
    print("{:.0f}={:.0f}*{:.0f}".format(number_to_check, number_to_check / i, i))

if len(argv) != 2:
    exit()
def find_and_times(n):
    """factor each
    n given
    """
    for i in range(1, n):
        if n == ((n // i) * i):
            print("{}={}*{}".format(n, (n // i), i))
            break

try:
    with open(argv[1]) as file:
        line = file.readline()

        while line != "":
            number_to_check = int(line.split('\n')[0])
            factorize(number_to_check)
            line = file.readline()
except:
    pass
def fac_list(ls):
    """factor each
    num in ls
    """
    for i in ls:
        find_and_times(i)


if len(argv) == 2:
    fac_list(open_read_file(argv[1]))
